"""Script to create Week 3 and Week 4 EDA notebooks using nbformat."""
import nbformat as nbf
import json

# ── Helpers ───────────────────────────────────────────────────────────────────

def md(text):
    return nbf.v4.new_markdown_cell(text)

def code(text):
    return nbf.v4.new_code_cell(text)

def write_notebook(nb, path):
    with open(path, "w") as f:
        nbf.write(nb, f)
    print(f"Created: {path}")


# ─────────────────────────────────────────────────────────────────────────────
# NOTEBOOK 1: Week 3 — Raw Event Exploration
# ─────────────────────────────────────────────────────────────────────────────

nb3 = nbf.v4.new_notebook()
nb3["metadata"] = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.14.5"},
}

nb3.cells = [

md("""\
# Week 3: Exploring the Synthetic Event Dataset

Before building any machine learning models, you need to know your data inside out. This notebook
explores the raw synthetic event dataset generated by `generate_events.py` — 50,000 events across
200 simulated trading platform users, with 10 distinct fraud patterns deliberately injected.

The goal here isn't to build anything. It's to get a feel for what normal looks like, what
suspicious looks like, and where the meaningful signals are hiding.\
"""),

code("""\
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

plt.style.use("seaborn-v0_8-whitegrid")
sns.set_palette("muted")
Path("../reports/figures").mkdir(parents=True, exist_ok=True)

df = pd.read_csv("../data/raw/events.csv", parse_dates=["timestamp"])
print(f"Shape: {df.shape}")
print(f"Date range: {df['timestamp'].min().date()} to {df['timestamp'].max().date()}")
print(f"Unique users: {df['user_id'].nunique()}")
print(f"\\nNull counts per column (showing only non-zero):")
null_counts = df.isnull().sum()
print(null_counts[null_counts > 0].to_string())\
"""),

md("""\
## Dataset Overview

The dataset has **50,000 rows and 31 columns**, covering January 1 to March 30, 2024. Most of the
null values are expected — event-specific columns like `trade_volume` only get populated for
trade events, `click_rate_per_min` only for session events, etc. These nulls aren't a data quality
problem; they're structural.

Two columns tell us whether a row is fraud: `is_anomalous` (0/1 flag) and `anomaly_type` (the
specific fraud category, or `"none"` for normal events). These exist because we injected the
anomalies ourselves — in a real system, you'd never have these labels for every event.\
"""),

code("""\
# ── 1. Event type distribution ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

vc = df["event_type"].value_counts()
colors = sns.color_palette("muted", len(vc))
bars = axes[0].bar(vc.index, vc.values, color=colors)
axes[0].set_title("Events by Type", fontsize=13, fontweight="bold")
axes[0].set_xlabel("Event Type")
axes[0].set_ylabel("Count")
for bar, v in zip(bars, vc.values):
    axes[0].text(bar.get_x() + bar.get_width()/2, v + 150,
                 f"{v:,}", ha="center", fontsize=9)

cross = df.groupby(["event_type", "is_anomalous"]).size().unstack(fill_value=0)
cross.columns = ["Normal", "Anomalous"]
cross.plot(kind="bar", stacked=True, ax=axes[1], color=["#4c9be8", "#e84c4c"], edgecolor="white")
axes[1].set_title("Normal vs Anomalous per Event Type", fontsize=13, fontweight="bold")
axes[1].set_xlabel("")
axes[1].legend(loc="upper right")
axes[1].tick_params(axis="x", rotation=30)

plt.tight_layout()
plt.savefig("../reports/figures/event_type_distribution.png", dpi=150, bbox_inches="tight")
plt.show()
print(df["event_type"].value_counts())\
"""),

md("""\
**Observation:** Trades dominate at ~35% — makes sense for a trading platform. KYC changes are
the rarest at ~6%, which also tracks (people don't update their identity documents often).
The anomalous events appear in every category, though some (like `deposit` and `withdrawal`) have
a noticeably higher anomalous fraction due to fraud patterns like the deposit-withdrawal cycler
and the structurer.\
"""),

code("""\
# ── 2. Anomaly type breakdown ─────────────────────────────────────────────────
anom_df = df[df["is_anomalous"] == 1]
vc_anom = anom_df["anomaly_type"].value_counts()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

colors_anom = sns.color_palette("tab10", len(vc_anom))
bars = axes[0].barh(vc_anom.index, vc_anom.values, color=colors_anom)
axes[0].set_title("Anomalous Events by Fraud Pattern", fontsize=12, fontweight="bold")
axes[0].set_xlabel("Event Count")
axes[0].invert_yaxis()
for bar, val in zip(bars, vc_anom.values):
    axes[0].text(val + 5, bar.get_y() + bar.get_height()/2,
                 str(val), va="center", fontsize=9)

# Pie chart of anomaly distribution
axes[1].pie(vc_anom.values, labels=[l.replace("_", "\\n") for l in vc_anom.index],
            colors=colors_anom, autopct="%1.1f%%", startangle=140,
            textprops={"fontsize": 8})
axes[1].set_title("Fraction of Anomalous Events\\nby Fraud Type", fontsize=12, fontweight="bold")

plt.tight_layout()
plt.savefig("../reports/figures/anomaly_type_breakdown.png", dpi=150, bbox_inches="tight")
plt.show()
print(f"Total anomalous events: {len(anom_df):,} / {len(df):,} ({len(anom_df)/len(df)*100:.1f}%)")
print(f"Total anomalous users: {anom_df['user_id'].nunique()} / {df['user_id'].nunique()}")\
"""),

md("""\
**Observation:** 5,032 out of 50,000 events are flagged as anomalous — roughly 10%. The
distribution across fraud types is fairly even, which is by design: the generator cycles through
all 10 types and assigns 2 users per type. Wash traders generate the most events (524) because
the generator creates 10 trades per user × 2 users, plus all their background activity is also
labeled anomalous. Dormant withdrawers have the fewest injected burst events (3 withdrawals per
user).\
"""),

code("""\
# ── 3. Geographic and device distribution ─────────────────────────────────────
login_df = df[df["event_type"] == "login"]

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

country_vc = login_df["country"].value_counts()
axes[0].bar(country_vc.index, country_vc.values, color=sns.color_palette("pastel", len(country_vc)))
axes[0].set_title("Login Events by Country", fontsize=12, fontweight="bold")
axes[0].set_ylabel("Login Count")
axes[0].set_xlabel("Country Code")

device_vc = login_df["device"].value_counts()
axes[1].barh(device_vc.index, device_vc.values, color=sns.color_palette("pastel", len(device_vc)))
axes[1].set_title("Logins by Device Type", fontsize=12, fontweight="bold")
axes[1].set_xlabel("Login Count")
axes[1].invert_yaxis()

plt.tight_layout()
plt.savefig("../reports/figures/geo_device_distribution.png", dpi=150, bbox_inches="tight")
plt.show()
print("Country breakdown:"); print(country_vc.to_string())
print("\\nDevice breakdown:"); print(device_vc.to_string())\
"""),

md("""\
**Observation:** Countries are fairly uniformly distributed since users are randomly assigned home
countries. The device mix looks realistic — Chrome on Windows and Safari on Mac lead, with mobile
apps trailing. If you saw a real platform heavily skewed toward one country or device, that would
itself be a signal worth investigating.\
"""),

code("""\
# ── 4. Normal vs anomalous trade volume ───────────────────────────────────────
trade_df = df[df["event_type"] == "trade"].copy()
trade_df["user_type"] = trade_df["is_anomalous"].map({0: "Normal", 1: "Anomalous"})

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

sns.boxplot(data=trade_df, x="user_type", y="trade_volume", ax=axes[0],
            palette={"Normal": "#4c9be8", "Anomalous": "#e84c4c"})
axes[0].set_yscale("log")
axes[0].set_title("Trade Volume: Normal vs Anomalous", fontsize=12, fontweight="bold")
axes[0].set_ylabel("Trade Volume (log scale)")
axes[0].set_xlabel("")

# The key signal: trade_volume_vs_baseline
trade_df_notna = trade_df.dropna(subset=["trade_volume_vs_baseline"])
for label, color in [("Normal", "#4c9be8"), ("Anomalous", "#e84c4c")]:
    sub = trade_df_notna[trade_df_notna["user_type"]==label]["trade_volume_vs_baseline"]
    sub_clipped = sub.clip(upper=25)
    axes[1].hist(sub_clipped, bins=60, alpha=0.6, color=color,
                 label=f"{label} (n={len(sub):,})", density=True)
axes[1].set_title("Trade Volume vs User Baseline", fontsize=12, fontweight="bold")
axes[1].set_xlabel("Volume / Typical Volume (ratio)")
axes[1].set_ylabel("Density")
axes[1].axvline(x=3, color="orange", linestyle="--", alpha=0.8, label="3× baseline")
axes[1].axvline(x=10, color="red", linestyle="--", alpha=0.8, label="10× baseline")
axes[1].legend(fontsize=9)

plt.tight_layout()
plt.savefig("../reports/figures/trade_volume_analysis.png", dpi=150, bbox_inches="tight")
plt.show()

wash_trades = df[(df["anomaly_type"]=="wash_trader") & (df["event_type"]=="trade")]
print(f"Wash trader vol_vs_baseline range: {wash_trades['trade_volume_vs_baseline'].min():.1f}x to {wash_trades['trade_volume_vs_baseline'].max():.1f}x")
print(f"Wash trader positive PnL: {(wash_trades['pnl']>0).sum()}/{len(wash_trades)}")\
"""),

md("""\
**Observation:** The log-scale boxplot shows wash traders (anomalous) generating trades at
significantly higher absolute volumes. The ratio plot is more revealing: normal users trade very
close to their typical volume (around 1.0×), while wash traders hit 10-20× their baseline. A
10× volume spike compared to a user's own history is a strong red flag. Interestingly, wash
traders don't always profit — 113 out of 201 wash trade events show positive PnL. That's ~56%,
only slightly above chance. The signal here is volume, not win rate.\
"""),

code("""\
# ── 5. Click rate analysis — bot detection ────────────────────────────────────
sess_df = df[df["event_type"] == "session"].dropna(subset=["click_rate_per_min"])

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

# All sessions on log scale
normal_cr = sess_df[sess_df["is_anomalous"]==0]["click_rate_per_min"]
axes[0].hist(normal_cr, bins=60, color="#4c9be8", alpha=0.8, label="Normal sessions")
bot_burst = df[(df["anomaly_type"]=="bot_trader") & (df["event_type"]=="session") &
               (df["click_rate_per_min"] > 100)]["click_rate_per_min"]
axes[0].hist(bot_burst, bins=20, color="#e84c4c", alpha=0.9, label=f"Bot bursts (n={len(bot_burst)})")
axes[0].set_yscale("log")
axes[0].set_title("Click Rate: Normal Sessions vs Bot Bursts", fontsize=12, fontweight="bold")
axes[0].set_xlabel("Clicks per Minute")
axes[0].set_ylabel("Count (log scale)")
axes[0].axvline(x=100, color="orange", linestyle="--", alpha=0.8, label="100/min threshold")
axes[0].legend(fontsize=9)

# Right: zoom into the normal range
axes[1].hist(normal_cr[normal_cr <= 20], bins=50, color="#4c9be8", alpha=0.8)
axes[1].set_title("Normal Session Click Rate (zoomed)", fontsize=12, fontweight="bold")
axes[1].set_xlabel("Clicks per Minute")
axes[1].set_ylabel("Count")
p50 = normal_cr.quantile(0.50)
p95 = normal_cr.quantile(0.95)
axes[1].axvline(p50, color="green", linestyle="--", label=f"Median: {p50:.1f}")
axes[1].axvline(p95, color="orange", linestyle="--", label=f"95th pct: {p95:.1f}")
axes[1].legend(fontsize=9)

plt.tight_layout()
plt.savefig("../reports/figures/click_rate_analysis.png", dpi=150, bbox_inches="tight")
plt.show()
print(f"Normal click rate: median={normal_cr.median():.1f}, 95th pct={normal_cr.quantile(0.95):.1f}, 99th={normal_cr.quantile(0.99):.1f}/min")
print(f"Bot burst sessions: {len(bot_burst)}, range: {bot_burst.min():.0f}-{bot_burst.max():.0f}/min")\
"""),

md("""\
**Observation:** This is one of the cleanest signals in the dataset. Normal sessions max out at
around 10-15 clicks/minute at the 99th percentile. The bot burst sessions jump to 258-2205
clicks/minute — that's 20-170× the normal range. Only 16 sessions in total hit above 100/min,
and they're all from the bot_trader users.

The challenge is that bot_trader users also generate many normal sessions. If you set a threshold
at 100/min, you'd catch only the 16 burst sessions and miss all the normal activity from the same
user. A user-level model that tracks their session history would be far more effective.\
"""),

code("""\
# ── 6. Temporal activity heatmap ──────────────────────────────────────────────
pivot = df.groupby(["hour_of_day", "day_of_week"]).size().unstack(fill_value=0)
day_names = {0: "Mon", 1: "Tue", 2: "Wed", 3: "Thu", 4: "Fri", 5: "Sat", 6: "Sun"}
pivot.columns = [day_names[d] for d in pivot.columns]

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

sns.heatmap(pivot, cmap="YlOrRd", ax=axes[0], linewidths=0.3,
            cbar_kws={"label": "Event Count"})
axes[0].set_title("All Events — Hour × Day of Week", fontsize=12, fontweight="bold")
axes[0].set_xlabel("Day of Week")
axes[0].set_ylabel("Hour of Day (UTC)")

# Bot trader sessions specifically
bot_sess = df[(df["anomaly_type"]=="bot_trader") & (df["event_type"]=="session")]
bot_pivot = bot_sess.groupby(["hour_of_day", "day_of_week"]).size().unstack(fill_value=0)
bot_pivot.columns = [day_names.get(d, d) for d in bot_pivot.columns]
# reindex to show full 0-23 range
bot_pivot = bot_pivot.reindex(range(24), fill_value=0)
sns.heatmap(bot_pivot, cmap="Reds", ax=axes[1], linewidths=0.3,
            cbar_kws={"label": "Session Count"})
axes[1].set_title("Bot Trader Sessions Only — Hour × Day", fontsize=12, fontweight="bold")
axes[1].set_xlabel("Day of Week")
axes[1].set_ylabel("Hour of Day (UTC)")

plt.tight_layout()
plt.savefig("../reports/figures/temporal_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()\
"""),

md("""\
**Observation:** The overall event distribution is fairly uniform across the week — expected since
the data was generated with random timestamps. The bot trader heatmap is more interesting: the
sessions cluster tightly in the 2-4 AM UTC window (hours 2, 3, 4), with activity hitting on
specific days. Real platforms see bots operating during off-peak hours precisely because lower
human activity means less competition and more predictable market conditions.\
"""),

code("""\
# ── 7. Fraud signal overview — one subplot per anomaly type ──────────────────
anomaly_signals = [
    ("ip_hopper",                 "timezone_gap_hours",       "Timezone Gap (hrs)"),
    ("wash_trader",               "trade_volume_vs_baseline",  "Vol vs Baseline (×)"),
    ("deposit_withdrawal_cycler", "is_immediate_withdrawal",   "Immediate Withdrawal"),
    ("bot_trader",                "click_rate_per_min",        "Clicks / Min"),
    ("structurer",                "amount",                    "Deposit Amount ($)"),
    ("brute_forcer",              "failed_attempts",           "Failed Login Attempts"),
    ("dormant_withdrawer",        "amount",                    "Withdrawal Amount ($)"),
    ("consistent_winner",         "trade_duration_seconds",    "Trade Duration (s)"),
    ("device_switcher",           "device",                    "Device Used"),
    ("kyc_manipulator",           "kyc_change_type",           "KYC Change Type"),
]

fig, axes = plt.subplots(2, 5, figsize=(22, 8))
axes = axes.flatten()
normal_df = df[df["is_anomalous"] == 0]

for idx, (atype, col, label) in enumerate(anomaly_signals):
    ax = axes[idx]
    anom_sub  = df[df["anomaly_type"] == atype].dropna(subset=[col])
    norm_sub  = normal_df.dropna(subset=[col])
    title = atype.replace("_", " ").title()

    is_categorical = not pd.api.types.is_numeric_dtype(df[col])
    if is_categorical:
        vc = anom_sub[col].value_counts().head(5)
        ax.bar(range(len(vc)), vc.values, color="#e84c4c", alpha=0.85)
        ax.set_xticks(range(len(vc)))
        ax.set_xticklabels(vc.index, rotation=35, ha="right", fontsize=7)
    else:
        clip_n = norm_sub[col].quantile(0.99)
        clip_a = anom_sub[col].quantile(0.99)
        ax.hist(norm_sub[col].clip(upper=clip_n), bins=40, alpha=0.5,
                color="#4c9be8", label="Normal", density=True)
        ax.hist(anom_sub[col].clip(upper=clip_a), bins=40, alpha=0.7,
                color="#e84c4c", label=atype, density=True)
        if idx == 0: ax.legend(fontsize=7)

    ax.set_title(title, fontsize=9, fontweight="bold")
    ax.set_xlabel(label, fontsize=8)
    ax.set_ylabel("Count" if is_categorical else "Density", fontsize=8)
    ax.tick_params(labelsize=7)

plt.suptitle("Key Discriminating Signal for Each Fraud Pattern",
             fontsize=14, fontweight="bold", y=1.01)
plt.tight_layout()
plt.savefig("../reports/figures/anomaly_signals_overview.png", dpi=150, bbox_inches="tight")
plt.show()\
"""),

md("""\
## Key Observations

Looking across all 10 fraud patterns, a few signals stand out as particularly clean:

**Strongest signals:**
- **Bot trader**: click_rate_per_min of 258-2205/min vs normal max of ~15/min. On a log scale
  this is immediately visible. The 16 burst sessions are unmistakable.
- **Consistent winner**: trade_duration_seconds of 1-10s vs normal range of 60-3600s. No overlap.
- **Brute forcer**: failed_attempts reaches 5 before a successful login. Normal users never
  exceed 1 failed attempt.
- **Dormant withdrawer**: withdrawal amounts of $15,000-$43,217 vs normal withdrawals which are
  much lower.

**Subtler signals (harder to detect without context):**
- **Structurer**: deposits are in the $490-$999 range, but so are some normal deposits. The
  pattern only becomes clear when you look at the *sequence* — many deposits just below $1,000
  in quick succession. A single structurer deposit looks normal in isolation.
- **IP hopper**: timezone_gap_hours is 0-8. The signal is in the *rate* of country switching,
  not a single value. 8 different countries in 2 hours is the tell.
- **Device switcher**: each individual login uses a plausible device. The anomaly is that no
  two consecutive logins use the same device.

**Challenge for modeling (Week 5-6):** Most events from anomalous users look perfectly normal.
The fraud signal is concentrated in a small burst of events per user, surrounded by hundreds of
legitimate-looking events. An unsupervised model that sees these users as a whole might not flag
them at all — it needs to detect the anomalous EPISODES within the user's history.\
"""),

]

write_notebook(nb3, "notebooks/week3_events_exploration.ipynb")
print("Week 3 notebook created.")


# ─────────────────────────────────────────────────────────────────────────────
# NOTEBOOK 2: Week 4 — Feature Engineering & EDA
# ─────────────────────────────────────────────────────────────────────────────

nb4 = nbf.v4.new_notebook()
nb4["metadata"] = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.14.5"},
}

nb4.cells = [

md("""\
# Week 4: Feature Engineering & Exploratory Data Analysis

Raw event logs can't go directly into a machine learning model. A single login event tells us
almost nothing on its own — it's the pattern of logins over time that carries the signal.
Feature engineering is the process of transforming those raw events into numbers that capture
behavioral context: how active has this user been recently? Is their click rate unusually high?
Did they switch countries in their last 10 logins?

This notebook explores `features.csv` — the output of `feature_engineering.py`, which adds
23 behavioral features to the original 31 event columns.\
"""),

code("""\
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

plt.style.use("seaborn-v0_8-whitegrid")
sns.set_palette("muted")
Path("../reports/figures").mkdir(parents=True, exist_ok=True)

df_raw  = pd.read_csv("../data/raw/events.csv")
df      = pd.read_csv("../data/processed/features.csv", parse_dates=["timestamp"])

raw_cols   = set(df_raw.columns)
new_feats  = [c for c in df.columns if c not in raw_cols]
print(f"Original columns  : {len(raw_cols)}")
print(f"Engineered features: {len(new_feats)}")
print(f"Total columns     : {len(df.columns)}")
print(f"\\nNew features added:")
for f in new_feats:
    print(f"  + {f}")\
"""),

md("""\
## The 6 Feature Categories

Here's what each category captures and why it's useful for anomaly detection:

**1. Time-delta features** (`time_since_last_event_sec`, `time_since_last_login_sec`,
`time_since_last_deposit_sec`) — measures the gap between consecutive actions. A bot hammering
the platform every few seconds shows up immediately here. A dormant account suddenly active after
months also becomes visible.

**2. Rolling window features** (`roll_5_trade_vol_mean`, `roll_10_pnl_mean`, etc.) — summarize
recent behavior using a sliding window of the last 5 or 10 events of that type. This is what lets
us say "this trade is 15× the user's recent average" rather than just "this trade is large."
User-relative comparison is what makes anomaly detection powerful.

**3. Burst count features** (`burst_count_5min`, `burst_count_30min`) — count events in a
rolling time window. Bots generating hundreds of requests per minute look completely different
from humans here.

**4. Login behavior features** (`unique_ips_last_10_logins`, `unique_countries_last_10_logins`,
`unique_devices_last_10_logins`, `rolling_failed_attempts_5`) — summarize login diversity. A
normal user uses 1-2 devices and stays in one country. An IP hopper shows up across 8+ countries
in their last 10 logins.

**5. Financial behavior features** (`roll_5_deposit_sum`, `withdrawal_to_deposit_ratio`) —
track deposit and withdrawal patterns. The money laundering signal (deposit → immediate
withdrawal) is captured directly by the ratio.

**6. Z-score features** (`trade_vol_zscore`, `pnl_zscore`, `amount_zscore`,
`session_duration_zscore`) — measure how many standard deviations a value is from that user's
own mean. This normalizes for user-specific differences. A |z| > 3 event is likely the anomaly,
regardless of the absolute value.\
"""),

code("""\
# ── Task 2: Temporal behavior ─────────────────────────────────────────────────
time_cols = ["time_since_last_event_sec", "time_since_last_login_sec",
             "time_since_last_deposit_sec"]

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
for i, col in enumerate(time_cols):
    data = df[df[col] > 0][col]
    clip_val = data.quantile(0.99)
    normal_d = df[(df[col] > 0) & (df["is_anomalous"]==0)][col].clip(upper=clip_val)
    anom_d   = df[(df[col] > 0) & (df["is_anomalous"]==1)][col].clip(upper=clip_val)
    axes[i].hist(normal_d, bins=60, alpha=0.5, color="#4c9be8", label="Normal", density=True)
    axes[i].hist(anom_d,   bins=60, alpha=0.6, color="#e84c4c", label="Anomalous", density=True)
    med = data.median()
    axes[i].axvline(med, color="green", linestyle="--", label=f"Median: {med:.0f}s")
    axes[i].set_title(col.replace("_", " ").title(), fontsize=9, fontweight="bold")
    axes[i].set_xlabel("Seconds")
    axes[i].set_ylabel("Density")
    axes[i].legend(fontsize=7)

plt.suptitle("Time-Delta Feature Distributions", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("../reports/figures/time_delta_features.png", dpi=150, bbox_inches="tight")
plt.show()

for col in time_cols:
    data = df[df[col] > 0][col]
    print(f"{col}: median={data.median():.0f}s, 95th={data.quantile(0.95):.0f}s, max={data.max():.0f}s")\
"""),

md("""\
**Observation:** The time-delta distributions show heavy right tails — most consecutive events
happen within seconds or minutes, but there are long stretches of inactivity too. The normal and
anomalous distributions largely overlap here, which means these features alone won't distinguish
fraud. They become useful in combination with other features (e.g., very short gaps during a bot
session + unusually high burst count).\
"""),

code("""\
# ── Task 3: Burst count features ─────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 4))

for i, (col, label) in enumerate([("burst_count_5min",  "Events in last 5 min"),
                                    ("burst_count_30min", "Events in last 30 min")]):
    normal_d = df[df["is_anomalous"]==0][col]
    anom_d   = df[df["is_anomalous"]==1][col]
    p95_norm = normal_d.quantile(0.95)
    axes[i].hist(normal_d, bins=40, alpha=0.5, color="#4c9be8", label="Normal", density=True)
    axes[i].hist(anom_d,   bins=40, alpha=0.6, color="#e84c4c", label="Anomalous", density=True)
    axes[i].axvline(p95_norm, color="orange", linestyle=":",
                    alpha=0.9, label=f"Normal 95th pct: {p95_norm:.0f}")
    axes[i].set_title(f"Burst Activity: {label}", fontsize=11, fontweight="bold")
    axes[i].set_xlabel(col)
    axes[i].set_ylabel("Density")
    axes[i].legend(fontsize=8)

plt.tight_layout()
plt.savefig("../reports/figures/burst_features.png", dpi=150, bbox_inches="tight")
plt.show()

for col in ["burst_count_5min", "burst_count_30min"]:
    n95 = df[df["is_anomalous"]==0][col].quantile(0.95)
    a_max = df[df["is_anomalous"]==1][col].max()
    print(f"{col}: normal 95th={n95:.1f}, anomalous max={a_max:.0f}")\
"""),

md("""\
**Observation:** The burst features are quite compressed — most users generate 1-2 events in a
5-minute window. The bot trader anomaly creates up to 3 events in 5 minutes from its burst
sessions, but the effect is subtle because the bot's session bursts happen over a ~24-minute
window (8 sessions × 3-minute intervals), so `burst_count_5min` only catches the closely spaced
ones. `burst_count_30min` better captures the bot pattern. This suggests the feature could be
improved with a longer window — something to try in Week 5.\
"""),

code("""\
# ── Task 4: Login behavior features ──────────────────────────────────────────
login_feat = df[df["event_type"]=="login"].copy()
login_feat = login_feat.dropna(subset=["unique_ips_last_10_logins"])
login_feat["user_type"] = login_feat["is_anomalous"].map({0: "Normal", 1: "Anomalous"})

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
login_cols = ["unique_ips_last_10_logins",
              "unique_countries_last_10_logins",
              "unique_devices_last_10_logins"]
short_labels = ["Unique IPs\\n(last 10 logins)",
                "Unique Countries\\n(last 10 logins)",
                "Unique Devices\\n(last 10 logins)"]

for i, (col, lbl) in enumerate(zip(login_cols, short_labels)):
    sns.boxplot(data=login_feat, x="user_type", y=col, ax=axes[i],
                palette={"Normal": "#4c9be8", "Anomalous": "#e84c4c"})
    normal_med = login_feat[login_feat["user_type"]=="Normal"][col].median()
    anom_med   = login_feat[login_feat["user_type"]=="Anomalous"][col].median()
    axes[i].set_title(lbl, fontsize=10, fontweight="bold")
    axes[i].set_xlabel("")
    axes[i].set_ylabel("Count")
    axes[i].set_title(f"{lbl}\\nNormal med={normal_med:.1f}  Anomalous med={anom_med:.1f}",
                      fontsize=9, fontweight="bold")

plt.suptitle("Login Diversity Features: Normal vs Anomalous", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("../reports/figures/login_anomaly_features.png", dpi=150, bbox_inches="tight")
plt.show()

# Specifically check ip_hopper
hop_logins = login_feat[login_feat["anomaly_type"]=="ip_hopper"]
print(f"IP hopper unique_countries_last_10: mean={hop_logins['unique_countries_last_10_logins'].mean():.2f}, max={hop_logins['unique_countries_last_10_logins'].max():.0f}")
print(f"Normal unique_countries_last_10: mean={login_feat[login_feat['is_anomalous']==0]['unique_countries_last_10_logins'].mean():.2f}")\
"""),

md("""\
**Observation:** The login diversity features are where the IP hopper pattern becomes quantifiable.
IP hoppers show a noticeably higher number of unique countries across their last 10 logins — the
boxplot shows their median is above normal. Device switchers similarly show elevated
`unique_devices_last_10_logins`. Most normal users stick to 1 device; the device switcher
deliberately rotates through all 5 device types.

One thing I noticed: the `unique_ips_last_10_logins` feature is less discriminating than
`unique_countries_last_10_logins` because some anomalous users (wash traders, structurers) use
static IPs for their normal events, which anchor the rolling window. Country switching is a
stronger signal for the IP hopper pattern specifically.\
"""),

code("""\
# ── Task 5: Financial behavior features ───────────────────────────────────────
fin_df = df[df["event_type"].isin(["deposit", "withdrawal"])].copy()
fin_df["user_type"] = fin_df["is_anomalous"].map({0: "Normal", 1: "Anomalous"})

fig, axes = plt.subplots(1, 2, figsize=(13, 4))

# Withdrawal-to-deposit ratio (clip extreme values for visualization)
ratio_df = fin_df[fin_df["event_type"]=="withdrawal"].copy()
ratio_df = ratio_df[ratio_df["withdrawal_to_deposit_ratio"] > 0]
# clip at 10 for readability (extreme values are expected for dormant withdrawers)
for label, color in [("Normal", "#4c9be8"), ("Anomalous", "#e84c4c")]:
    sub = ratio_df[ratio_df["user_type"]==label]["withdrawal_to_deposit_ratio"].clip(upper=10)
    axes[0].hist(sub, bins=50, alpha=0.6, color=color,
                 label=f"{label} (n={len(sub):,})", density=True)
axes[0].axvline(1.0, color="black", linestyle="--", alpha=0.8, label="1.0 (break-even)")
axes[0].set_title("Withdrawal-to-Deposit Ratio\\n(clipped at 10×)", fontsize=11, fontweight="bold")
axes[0].set_xlabel("Withdrawal / Rolling Deposit Sum")
axes[0].set_ylabel("Density")
axes[0].legend(fontsize=8)

# Rolling deposit sum for deposit events
dep_df = fin_df[fin_df["event_type"]=="deposit"].dropna(subset=["roll_5_deposit_sum"])
dep_df = dep_df[dep_df["roll_5_deposit_sum"] > 0]
sns.boxplot(data=dep_df, x="user_type", y="roll_5_deposit_sum", ax=axes[1],
            palette={"Normal": "#4c9be8", "Anomalous": "#e84c4c"})
axes[1].set_yscale("log")
axes[1].set_title("Rolling 5-Deposit Sum", fontsize=11, fontweight="bold")
axes[1].set_ylabel("Sum ($, log scale)")
axes[1].set_xlabel("")

plt.tight_layout()
plt.savefig("../reports/figures/financial_features.png", dpi=150, bbox_inches="tight")
plt.show()

# Stats on deposit-withdrawal cycler
dwc = df[(df["anomaly_type"]=="deposit_withdrawal_cycler") & (df["event_type"]=="withdrawal")]
print(f"Deposit-withdrawal cycler ratio: {dwc['withdrawal_to_deposit_ratio'].describe()}")\
"""),

md("""\
**Observation:** The withdrawal-to-deposit ratio captures the deposit-withdrawal cycler pattern
well. When `roll_5_deposit_sum` is small and a withdrawal is large, the ratio spikes. The
extreme values (clipped at 10× for visualization) mostly come from dormant withdrawers who have
no recent deposits at all — dividing by near-zero gives astronomical ratios, which are actually
informative.

The cycler pattern itself shows up clearly: their ratio is consistently close to or above 1.0,
meaning they withdraw nearly everything they deposit. Legitimate users typically withdraw less
than they deposit over any rolling window.\
"""),

code("""\
# ── Task 6: Z-score analysis ──────────────────────────────────────────────────
zscore_cols = ["trade_vol_zscore", "pnl_zscore", "amount_zscore", "session_duration_zscore"]
fig, axes = plt.subplots(2, 2, figsize=(13, 9))
axes = axes.flatten()

for i, col in enumerate(zscore_cols):
    data = df.dropna(subset=[col])
    normal_z = data[data["is_anomalous"]==0][col]
    anom_z   = data[data["is_anomalous"]==1][col]
    clip_val = 8

    axes[i].hist(normal_z.clip(-clip_val, clip_val), bins=80, alpha=0.5,
                 color="#4c9be8", label="Normal", density=True)
    axes[i].hist(anom_z.clip(-clip_val, clip_val),   bins=80, alpha=0.6,
                 color="#e84c4c", label="Anomalous", density=True)
    axes[i].axvline( 2, color="orange", linestyle=":", alpha=0.8)
    axes[i].axvline(-2, color="orange", linestyle=":", alpha=0.8, label="|z|=2")
    axes[i].axvline( 3, color="red",    linestyle=":", alpha=0.8)
    axes[i].axvline(-3, color="red",    linestyle=":", alpha=0.8, label="|z|=3")
    axes[i].set_title(col, fontsize=10, fontweight="bold")
    axes[i].set_xlabel("Z-Score")
    axes[i].set_ylabel("Density")
    axes[i].legend(fontsize=8)

    b2 = (data[col].abs() > 2).sum()
    b3 = (data[col].abs() > 3).sum()
    print(f"{col}: |z|>2 = {b2} ({b2/len(data)*100:.1f}%)  |z|>3 = {b3} ({b3/len(data)*100:.1f}%)")

plt.suptitle("Z-Score Distributions: Normal vs Anomalous Events",
             fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("../reports/figures/zscore_analysis.png", dpi=150, bbox_inches="tight")
plt.show()\
"""),

md("""\
**Observation:** All four z-score features follow roughly normal distributions for both classes,
which is expected since z-scores measure deviation from a user's own mean. The anomalous events
don't show a dramatically different distribution overall — most of the time, even anomalous
users generate events that are within ±2 standard deviations of their own history.

This is the core challenge: the fraud signal is localized to a small number of extreme events per
user. `trade_vol_zscore` shows the strongest separation — consistent winners and wash traders
generate trades with |z|>3 more frequently than normal users. Only about 0.1% of events exceed
|z|=3, but those 50-odd events are disproportionately from anomalous users.\
"""),

code("""\
# ── Task 7: Correlation heatmap ───────────────────────────────────────────────
num_features = [
    "trade_volume", "pnl", "amount", "click_rate_per_min", "failed_attempts",
    "timezone_gap_hours", "trade_volume_vs_baseline", "session_duration_mins",
    "time_since_last_event_sec", "burst_count_5min", "burst_count_30min",
    "unique_ips_last_10_logins", "unique_countries_last_10_logins",
    "withdrawal_to_deposit_ratio", "trade_vol_zscore", "pnl_zscore",
    "amount_zscore", "roll_5_trade_vol_mean", "roll_10_trade_vol_mean",
]
corr_df = df[num_features].dropna()
corr_matrix = corr_df.corr()

fig, ax = plt.subplots(figsize=(15, 12))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, cmap="RdBu_r", center=0,
            annot=True, fmt=".1f", annot_kws={"size": 7},
            ax=ax, square=True, linewidths=0.3, vmin=-1, vmax=1,
            cbar_kws={"label": "Pearson r", "shrink": 0.8})
ax.set_title("Feature Correlation Matrix (lower triangle)", fontsize=14, fontweight="bold")
plt.tight_layout()
plt.savefig("../reports/figures/correlation_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()

# Print strongest correlations (r > 0.3 or r < -0.3)
corr_pairs = []
for i in range(len(corr_matrix.columns)):
    for j in range(i+1, len(corr_matrix.columns)):
        r = corr_matrix.iloc[i, j]
        if abs(r) > 0.3:
            corr_pairs.append((corr_matrix.columns[i], corr_matrix.columns[j], r))
corr_pairs.sort(key=lambda x: abs(x[2]), reverse=True)
print("Feature pairs with |r| > 0.3:")
for a, b, r in corr_pairs[:10]:
    print(f"  {a}  ↔  {b}:  r={r:.2f}")\
"""),

md("""\
**Correlation observations:**
- `roll_5_trade_vol_mean` and `roll_10_trade_vol_mean` are highly correlated — expected, they
  summarize the same underlying signal over different windows. In a final model, keeping both may
  be redundant.
- `burst_count_5min` and `burst_count_30min` are moderately correlated, but not as strongly as
  expected — the 5-minute window captures short bursts that the 30-minute window dilutes.
- `trade_volume` and `trade_vol_zscore` have a weaker correlation than you'd expect, which is
  actually good: the z-score has normalized out the user-level differences, so a high z-score
  isn't just "this user always trades big."
- `withdrawal_to_deposit_ratio` shows almost no correlation with anything else — it captures a
  completely independent behavioral signal, which makes it particularly valuable as a model
  feature.\
"""),

code("""\
# ── Challenge: User behavioral profiles (5 users) ─────────────────────────────
normal_user  = df[df["is_anomalous"]==0]["user_id"].value_counts().index[0]
profile_map  = {normal_user: "normal (most active)"}
for atype in ["wash_trader", "bot_trader", "ip_hopper", "structurer"]:
    u = df[df["anomaly_type"]==atype]["user_id"].unique()
    if len(u): profile_map[u[0]] = atype

print("Profiling these users:")
for uid, utype in profile_map.items():
    print(f"  {uid} → {utype}")

# Summary table
rows = []
for uid, utype in profile_map.items():
    u_df = df[df["user_id"]==uid]
    rows.append({
        "user_id"       : uid,
        "label"         : utype,
        "events"        : len(u_df),
        "event_types"   : ", ".join(u_df["event_type"].value_counts().head(3).index),
        "avg_trade_vol" : round(u_df["trade_volume"].mean(), 0),
        "max_burst_5min": int(u_df["burst_count_5min"].max()),
        "unique_countries": int(u_df["country"].nunique()),
        "max_click_rate" : round(u_df["click_rate_per_min"].max(), 0),
        "max_failed_logins": int(u_df["failed_attempts"].max()) if u_df["failed_attempts"].notna().any() else 0,
    })

profile_df = pd.DataFrame(rows)
print()
print(profile_df.to_string(index=False))\
"""),

code("""\
# Event timeline for 5 users
fig, axes = plt.subplots(1, 5, figsize=(22, 4), sharey=False)
event_colors = {
    "login": "#4c9be8", "trade": "#e84c4c", "deposit": "#2ecc71",
    "withdrawal": "#e67e22", "session": "#9b59b6"
}

for i, (uid, utype) in enumerate(profile_map.items()):
    u_df = df[df["user_id"]==uid].sort_values("timestamp")
    for j, etype in enumerate(["login", "trade", "deposit", "withdrawal", "session"]):
        mask = u_df["event_type"] == etype
        axes[i].scatter(u_df[mask]["timestamp"],
                        [j] * mask.sum(),
                        s=12, alpha=0.6, color=event_colors[etype], label=etype)

    axes[i].set_title(f"{utype}\\n({uid})", fontsize=8, fontweight="bold")
    axes[i].set_yticks(range(5))
    axes[i].set_yticklabels(["login","trade","deposit","withdrawal","session"], fontsize=7)
    axes[i].tick_params(axis="x", labelsize=6, rotation=35)
    axes[i].set_xlabel("Date", fontsize=7)

plt.suptitle("Event Activity Timelines — 5 User Profiles", fontsize=12, fontweight="bold")
plt.tight_layout()
plt.savefig("../reports/figures/user_profiles.png", dpi=150, bbox_inches="tight")
plt.show()\
"""),

md("""\
## Final Observations & What's Next

Profiling these 5 users drives home a key point: **anomalous users look normal most of the time**.
The wash trader (USER_0001) has a broadly similar activity timeline to the normal user — trades,
logins, deposits — the difference is buried in 20 burst trades where the volume is 10-20× their
baseline. The structurer (USER_0004) looks almost identical to a normal depositing user unless
you zoom into the deposit amounts and find the suspicious clustering below $1,000.

**Features that look most useful going into Week 5:**
- `trade_vol_zscore` and `trade_volume_vs_baseline` — directly capture the wash trader signal
- `unique_countries_last_10_logins` — best single feature for IP hoppers
- `rolling_failed_attempts_5` — brute forcers are clear outliers
- `withdrawal_to_deposit_ratio` — deposit-withdrawal cyclers have ratios near or above 1.0
- `click_rate_per_min` (raw, not rolled) — the bot burst sessions are obvious outliers

**What I'd investigate further:**
The `session_duration_zscore` showed almost no z-scores above ±3. Session duration might be
redundant given click_rate_per_min already captures bot behavior. Worth dropping in ablation
experiments during model training.

The class imbalance (~10% anomalous events) will matter in Week 5. Isolation Forest and LOF
are designed for this scenario — they don't need balanced classes — but the anomaly score
thresholds will need careful calibration to avoid flagging too many false positives.\
"""),

]

write_notebook(nb4, "notebooks/week4_feature_analysis.ipynb")
print("Week 4 notebook created.")
